apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: hongviet119/techtrends:latest
          imagePullPolicy: IfNotPresent
          name: techtrends
          ports:
            - containerPort: 3111
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3111
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3111
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"